### ISSUE TITLE
Absplice-RNA

### ISSUE THREAD

**Issue by yanwang271** [gagneurlab/absplice#15]
Hi,

I am trying to implement Absplice-RNA with a VCF file and RNAseq data from the same individual. I see the example code in README is made for Absplice-DNA. Could you point out how to use Absplice-RNA?

Thanks!
Yan

**Comment by WagnerNils** [comment]
Hi Yan,
thank you for your interest! I am currently setting up an example for AbSplice-RNA and will push it in the next days.

**Comment by WagnerNils** [comment]
Hi Yan, 
I added an example for AbSplice-RNA. Let me know if that works for you or if you need any further assistance.
All the best,
Nils

**Comment by yanwang271** [comment]
Thank you Nils!
Yan
