### ISSUE TITLE
T2T CHM13v2.0 (hs1) support

### ISSUE THREAD

**Issue by misshie** [gagneurlab/absplice#16]
Do you have any plans to officially support the T2T CHM13v2.0 (hs1) reference genome?

**Comment by WagnerNils** [comment]
Hi, as of now, we do not have concrete plans for that. However, it is straightforward, as long as you have RNA-seq data that is aligned to the specific genome version that you are interested in. 
To run AbSplice on another genome version, you would need to use tissue-specific SpliceMaps from that genome version. We used large RNA-seq cohorts from GTEx to create SpliceMaps, which were available for hg19 (GTEx v7) and hg38 (GTEx v8). If you have data available that is aligned to the T2T CHM13v2.0 (hs1) reference genome you can create SpliceMaps for any tissue and run AbSplice on them. To create SpliceMaps see the example notebook: [https://github.com/gagneurlab/splicemap/blob/master/notebooks/example.ipynb](https://github.com/gagneurlab/splicemap/blob/master/notebooks/example.ipynb)
Let me know if you need any further assistance on that.
