### ISSUE TITLE
Container Environment problem

### ISSUE THREAD

**Issue by ShaynaMallett** [gagneurlab/absplice#25]
Hello,

We are trying to make the container work on our slurm based HPCC. We don't have docker available to us on the server and images before allowing them to be used but .oci isn't accepted. They asked for a tar.gz version of the image to convert to a sif before we could use it. 

I installed docker locally, loaded the oci following the commands on git:
 `docker load -i absplice.oci 
  docker run -it --name absplice_container localhost/absplice:latest /bin/bash ` 
Then saved to a tar.gz 
`docker save localhost/absplice:latest | gzip > absplice_latest.tar.gz)`
The IT team created a sif for us using this and gave us the following command to load it. 
`singularity shell -B /n /n/app/singularity/containers/absplice.sif`

However, I run into an error trying to load the conda environment and conda init bash has no effect. Is this a problem with the system that we have to run it, the process of converting to tar.gz, or the image itself? And are there any recommendations for how to get around this problem? 

`[user@compute-node ~]$ singularity shell -B /n /path/to/absplice.sif
Apptainer> conda activate absplice_dock

CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.`

Thank you so much for your help!!!
Shayna

**Comment by neverov-am** [comment]
Dear @ShaynaMallett ,

Thank you for your question.

We are currently working on the AbSplice image for Singularity. The current version of the image allows you to run AbSplice with a full functionality. Here is the link to download it (you can use `wget`): https://zenodo.org/record/8192566/files/absplice.sif. You can use `source activate absplice_dock` to activate the environment inside the container.

However, we are still working on the implementation of the fast look up interface for SpliceAI (spliceai-rocksdb), which improves the computation time, inside the container. We will let you know when the new version of the image is available.

**Comment by ShaynaMallett** [comment]
Thank you so much for the update and the sif!
