### ISSUE TITLE
License

### ISSUE THREAD

**Issue by logust79** [gagneurlab/absplice#35]
Hello developers of absplice,

First of all many thanks for such a nice open-source project to improve splicing variant prediction and annotation.
I'm opening this issue because I struggle to find a license for using the code or precomputed scores. Do you happen to have a license for your wonderful project?

**Comment by WagnerNils** [comment]
Hi logust79,
thank you for your interest in our work and the nice feedback.
We added a license to the README. I hope this is helpful for you. Let me know if you need any further information on this.
