### ISSUE TITLE
SpliceAI running time

### ISSUE THREAD

**Issue by LucaBertoli** [gagneurlab/absplice#38]
Hello,
I an testing absplice on a human WGS  sample using default configurations (and tissues).
Currently I ran snakemake workflow inside the docker container using 20 threads.

MMSplice finished quite qwickly, but SpliceAI in running since 6 days and is still at chr2...

Is there a way for speeding SpliceAI up? 
Does SpliceAI scale up with the threads given as input to snakemake?

**Comment by neverov-am** [comment]
Dear @LucaBertoli ,

Thank you for your interest in AbSplice. SpliceAI tends to take significant amount of time to run. To speed it up, we provide the fast lookup interface spliceai_rocksdb that uses precomputed SpliceAI scores. You can enable it by simply changing the field `use_rocksdb` in the [config](https://github.com/gagneurlab/absplice/blob/master/example/workflow/config.yaml#L23) file to `True` and running Snakemake with `--use-conda` option. It will create a conda environment and download the precomputed SpliceAI scores (it will take some time – about 1 hour and use approximately 180GB of storage). This should then significantly speed up the computation.

Let me know if you need any further assistance on that.

**Comment by LucaBertoli** [comment]
Thanks for the answer.

What would be the difference with respect to using SpliceAI without precomputed scores?
What variants are present in the precomputed scores?

**Comment by neverov-am** [comment]
The precomputed scores contain all SNVs and indels up to 4 nucleotides. During the execution of the pipeline, scores for the variants present in the precomputed scores will be simply retrieved from the database. If the variant is not in the precomputed scores, it will be computed by running SpliceAI.

**Comment by LucaBertoli** [comment]
ok, so the output will be basically the same as running spliceAI from scratch, correct?

**Comment by neverov-am** [comment]
Yes, we do not skip variants that are not in the precomputed scores
